### ISSUE TITLE
Include reading list in course page

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#10]
As noted by @melyshu, at the moment we're not displaying any information about the course readings.

We should scrape these from the Registrar and display this information.

**Comment by bnsuoh** [comment]
Requested by Jessica Saint-Ulysse '19

**Comment by sebthedev** [comment]
Following commit 80256f28fd9a05bbe9f6972656993cdb5fdcbba1, now ready for the front-end team to implement displaying the readings.
