### ISSUE TITLE
Dealing with multiple semesters / course

### ISSUE THREAD

**Issue by melyshu** [sebthedev/PrincetonCourses#3]
Currently in the database there are multiple course objects for the same course offered in different semesters. I would propse to merge these so that each distinct course (by listing code) only has one entry, containing each offering of the course (by semester). This has the following added benefits:

1. There is no need to force the user to pick a semester to search in (it can be an optional filter).
2. Historical evaluation/instructor data can be easily found, not just the evaluation/instructor for a specific semester.
3. (an extension of the above) We might be able to interpolate evaluation data more effectively.

**Comment by sebthedev** [comment]
Essentially now resolved.
