### ISSUE TITLE
"OR" search

### ISSUE THREAD

**Issue by bnsuoh** [sebthedev/PrincetonCourses#30]
Requested by Michael Friedman '19

**Comment by sebthedev** [comment]
Can you elaborate on some anticipated cases in which this enhancement would be useful?

**Comment by bnsuoh** [comment]
Searching for distribution departments on a certain number of departments could be useful. The feedback given by the user says "SA and (ECO or POL)" as an example. This is similar to picking a distribution requirement in the registrar's page, and selecting checkboxes for certain departments.

**Comment by melyshu** [comment]
I think this is currently implemented (OR within search fields)... a search for 'sa eco pol' displays the correct search results. Not sure how to make this clear to the user though.

**Comment by sebthedev** [comment]
I think inadvertently implemented this when implementing #66, which shows only courses in a specified department when a search word exactly matches a department name.
