### ISSUE TITLE
Clicking on a course inside an instructor closes it

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#39]
When you search from an instructor, click on the instructor in search results to view all their courses, and then click on one of their courses, the instructor's list of courses snaps closed. If the list remained open, then it would be easier to jump between an instructor's various courses.

See this video for the current behaviour.

![ezgif-1-08be552568](https://cloud.githubusercontent.com/assets/1550185/25071536/61a6a30c-2288-11e7-8491-c2a0f83de208.gif)

**Comment by melyshu** [comment]
I think this was fixed with the alt-mobile merge.
