### ISSUE TITLE
Remember Search Sort Preference

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#46]
Use [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to magically remember by which order the user has most recently sorted the courses. 

We will need to take care to make sure this doesn't conflict with loading a page on which a sort order is already defined. For example, visiting [/?search=ethics&semester=1182&sort=rating](https://www.princetoncourses.com/?search=ethics&semester=1182&sort=rating) should sort search results by rating regardless of the user's most recent preference.

**Comment by bnsuoh** [comment]
Implemented with 2c8800e4891da366386b1281f43dc14174d697c7
