### ISSUE TITLE
detailed course object extracting most recent evaluation

### ISSUE THREAD

**Issue by melyshu** [sebthedev/PrincetonCourses#47]
refer to mat335 of fall2017  https://www.princetoncourses.com/course/1182004194

The search entry extracts its review from the most recent semester the professor taught the course (fall 2015) whereas the displayed evaluation is just the most recent semester with evaluations (fall 2016). Would it be nice to sync these up so that the detailed course object gives evaluations from the most recent semester the professor taught the course?

**Comment by sebthedev** [comment]
I was actually just working on this! Funny coincidence. See b4ace128008017d61d797cf48e28532eeac4db47.
