### ISSUE TITLE
Registrar Scraping Lacking Some Details When Text Formatted

### ISSUE THREAD

**Issue by melyshu** [sebthedev/PrincetonCourses#48]
refer to cos126 fall2017 https://www.princetoncourses.com/course/1182002051

The first entry of 'other information' is missing content found on the registrar's site at https://registrar.princeton.edu/course-offerings/course_details.xml?courseid=002051&term=1182.

The missing text is inside a <b> element.

**Comment by sebthedev** [comment]
Should be fixed by ba52df797894c783c38ae2fa8e6926df0ccc2445.
