### ISSUE TITLE
Possible Copyright Infringement

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#70]
There are two places in the app where we might be infringing copyright:
* The image on the splash page of the Princeton building ([princeton.jpg](https://github.com/sebthedev/PrincetonCourses/blob/3e88bb555373b97a160746091de0494538e7f99e/public/media/princeton.jpg)).
* The drawing of Calvin and Hobbes ([calvin_logo.gif](https://github.com/sebthedev/PrincetonCourses/blob/40b8a8bbd79b3f97255f0748cd6ae68bc58eedfa/public/media/calvin_logo.gif)).

We shouldn't infringe copyright. We should either create images/drawings ourselves or use images which we have a license to use (such as images released under a Creative Commons license).

**Comment by bnsuoh** [comment]
Princeton.jpg has Creative Commons license: https://creativecommons.org/licenses/by-nd/2.0/ 
We can think of alternatives for Calvin and Hobbes

**Comment by sebthedev** [comment]
For `princeton.jpg`, I think we should probably link directly to the photo's page on Flickr: https://www.flickr.com/photos/weinelt/33421088922/

**Comment by karabeara** [comment]
I'm trying out some different designs for the website, Seb. Should be done
with them by the end of the week.
