### ISSUE TITLE
Loading about page without logging in results in error

### ISSUE THREAD

**Issue by melyshu** [sebthedev/PrincetonCourses#71]
![image](https://cloud.githubusercontent.com/assets/24402574/25404775/26ba9390-29cf-11e7-968d-2661fa45576f.png)

My guess from playing around on localhost and dev is that about.ejs is rendered with the netid of the last login, regardless of whether or not the user is logged in (and who the user is). On localhost, the about page cannot be reached until a user has logged in. It continues to work after the user has logged out. The same occurred on dev.princetoncourses (when auto-deployed after pushing commits). On branch dev-navbar, the netid is showing on the about page when the page is rendered with one. I had a 'bsicim' rendered on the (deployed) about page in branch dev-navbar*. I noticed a problem when the netid was still displayed on the about page even after logging out.

*the commits were on dev and were deployed at dev.princetoncourses until I put them onto another branch and reverted them

**Comment by sebthedev** [comment]
I'm
