### ISSUE TITLE
Include "Reserved Seats" information

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#72]
Some courses, such as [LIN 250](https://registrar.princeton.edu/course-offerings/course_details.xml?courseid=013797&term=1182), have enrolment slots reserved for certain years. We should display this information in our app.

**Comment by sebthedev** [comment]
Courses with reserved seats now have a `reservedSeats` property which contains the needed data to be displayed on the frontend.

Reassigning to front end team for implementation.

**Comment by melyshu** [comment]
Scraper might need to be updated for courses like https://registrar.princeton.edu/course-offerings/course_details.xml?courseid=007216&term=1182

**Comment by melyshu** [comment]
also weird scraping for https://registrar.princeton.edu/course-offerings/course_details.xml?courseid=007255&term=1182

**Comment by sebthedev** [comment]
I've changed so that `reservedSeats` is now simply an array of strings representing the rows. This way we don't need to worry about whatever exact data the Registrar publishes. Thanks @melyshu for discovering these edge cases.

Re-scraping now.

**Comment by melyshu** [comment]
still some issues? https://dev.princetoncourses.com/course/1182008907

**Comment by sebthedev** [comment]
Gah. Sorry about this. The registrar has so many different formats! I'll
investigate.

**Comment by melyshu** [comment]
would it be easier to just scrape the whole chunk in one entry to be displayed?

**Comment by sebthedev** [comment]
That's what I'm trying to do, but the Registrar's HTML is very, very messy, which makes it hard to scrape. It's hopefully now fixed. I'm rescraping now.
