### ISSUE TITLE
Icons hard to see when course is active

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#74]
When a course is selected, it is a bit hard to distinguish the pin, heart, and warning triangle from the blue background. Can we tweak the colouring to make these icons more easily visible?
<img width="347" alt="screen shot 2017-04-26 at 09 07 23" src="https://cloud.githubusercontent.com/assets/1550185/25435990/e5e6f750-2a5f-11e7-94da-eff81baa4673.png">
<img width="351" alt="screen shot 2017-04-26 at 09 06 08" src="https://cloud.githubusercontent.com/assets/1550185/25435991/e5ec264e-2a5f-11e7-9192-b59f5df351e6.png">

**Comment by bnsuoh** [comment]
The icons now have lighter colors
