### ISSUE TITLE
Strange Courses with Catalog Number 90 In Database

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#8]
@melyshu noticed that there are some strange courses in the database with the catalog number 90 (such as COS 90, LIN 90, DAN 90). These seem to be in the OIT webfeed, but aren't mentioned anywhere else and seem not to be real courses.

We decided to change the course import script to ignore any courses with catalog numbers fewer than three characters.

**Comment by awonnacott** [comment]
Just so you know - these courses are reading courses, which are courses created at the beginning of the semester by student request. It would be useful to see them.

**Comment by sebthedev** [comment]
@awonnacott Can you tell us more about these? What does a "reading course" mean?

**Comment by sebthedev** [comment]
Hmm… more information here: https://odoc.princeton.edu/curriculum/special-academic-programs/reading-courses

**Comment by awonnacott** [comment]
[Here's some more info.](https://odoc.princeton.edu/curriculum/special-academic-programs/reading-courses)

For instance, this semester, a few math majors wanted to take COS 487, but it conflicted with MAT 335, which was a higher priority. So, they got permission from the instructor to create a new course number which met at a different time and covered the same material, problem sets, etc... Last semester, some people watned to take a course on topos theory, a branch of abstract math related to category theory and topology. They approached the professor teaching category theory and he agreed to meet with them 4:30-6:30 on Thursdays and teach them a course on topos theory.
