### ISSUE TITLE
Minimize requests when searching

### ISSUE THREAD

**Issue by panchr** [sebthedev/PrincetonCourses#87]
Currently, the frontend sends a request for every character change in input in the search box, which can result in a significant number of requests that slow down the user experience, because each requires updating the DOM and thus, a re-render. Also, multiple requests just have overhead, both for the client (in terms of data sent, time taken, etc.) and server (each will be processed even if the results are ignored).

I suggest one of few options for this:

1. Don't send the request until the user has not typed anything for a short period of time (25ms? you might want to test out different values to see what is not noticeable)
2. Use WebSockets instead of HTTP requests, which would be much faster and you can use less data (check out https://socket.io/ – it will fall back to `XMLHttpRequest` if web sockets are not supported on the browser)
3. Use local caching of courses and execute all queries locally in the browser. Recal does this, in that all the courses are sent in JSON to the user (and cached for a certain amount of time, like 30 minutes or a day or something like that).

I personally think 1 would be the easiest and most flexible solution.

**Comment by sebthedev** [comment]
Just implemented option 1 in commit bfd1a6fe6c9d2b36e5f6655cdc15864e43815954.
